#!/bin/bash

# create a directory with slides
# https://github.com/progrium/bashstyle

copy_files() {
  declare root="$1"
  echo "making ${root}"
  [ -d "${root}" ] || mkdir ${root}
  pushd "${root}"
  # -h is not standard - says don't follow directories
  ln -s -h ../_common/* .
  for t in ../_common/*-template* ; do
    echo "rm ${t##*/}"
    rm "${t##*/}"
    local name="${t%-template}"
    name="${name##*/}"
    [ ! -f ${t} ] || cp "${t}" "${name}"
  done
  bundle
  popd
}

if [[ "${#}" -eq 0 || "${1}" == "-h" ]] ; then
  echo "usage: ${0} slide_name"
else
  copy_files "$@"
fi
