filters:
- "HTML::Pipeline::DotFilter"
- "HTML::Pipeline::AutoAbbrFilter"
- "HTML::Pipeline::AbbrEmojiFilter"
- "HTML::Pipeline::MentionFilter"
- "HTML::Pipeline::AutolinkFilter"
requires:
- "tilt/erb"
- "html/pipeline/abbr"
- "html/pipeline/dot_filter"
