task :generate do
  puts "reveal-ck generate"
  `bundle exec reveal-ck generate`
end

task :serve => :generate do
  port=ENV["PORT"] || File.read("PORT").chomp
  puts "reveal-ck serve -p #{port}"
  exec("bundle exec reveal-ck serve -p #{port}")
end

task :default => :serve

# not sure if we still want this stuff:

require 'dothtml/dot_task'
Dothtml::DotTask.new do |t|
#  t.d3js      = "d3.v3.js"
#  t.style     = "style.css"
end

task :html do
  Dir.glob("*.dot").each do |f|
    Rake::Task[f.sub(/\.dot$/, '.html')].invoke
  end
end
