task :slides do
  puts "reveal-ck generate"
  `bundle exec reveal-ck generate`
end

task :default => :slides

# not sure if we still want this stuff:

require 'dothtml/dot_task'
Dothtml::DotTask.new do |t|
#  t.d3js      = "d3.v3.js"
#  t.style     = "style.css"
end

task :html do
  Dir.glob("*.dot").each do |f|
    Rake::Task[f.sub(/\.dot$/, '.html')].invoke
  end
end
